config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'hello_world#hello'

  get 'signup' => "users#new"
  post 'signup' => "users#create"
  get 'login' => "sessions#new"
  post "login" => "sessions#create"

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password validations: true
    validates :email, presence: true, uniqueness: true
    has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :current_user 

 
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def authenticate_user
        if @current_user == nil
            redirect_to login_path
        end
    end
end

app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
    def hello
        render "hello"
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user
  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def index
    @posts = current_user.posts.all
  end

  def edit
    @post = current_user.posts.find(params[:id])
    #  render plain: params.inspect
  end

  def update
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    # render plain: params.inspect
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  # render plain: params.inspect
  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

    user=  User.find_by(email: session_params[:email])
  
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to new_post_path
    else
      render :new
    end
  end
    
  private
    def session_params
      params.require(:session).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user=User.new
    end

    def create
        @user=User.new(user_params)
        session[:user_id]=@user.id
        if @user.save
            redirect_to root_url
        else
            render "new"
        end
    end
    
    private 
        def user_params
            params.require(:user).permit(:email, :password, :password_confirmation)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_world_helper.rb
module HelloWorldHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello_world/hello.html.erb
<h1>Hello World</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="posts-wrapper">
    <div class="posts-content">
        <% @posts.each do |p| %>
        <div class="post-content">
            <div class="post-content_element"><%=p.created_at.strftime('%Y年%m月%d日')%></div>
            <div class="post-content_element"><%= p.title %></div>
            <div class="post-content_element"><%= p.content%></div>
            <div class="post-content_btn">
                <div class="post-edit_btn">
                    <%=link_to "編集", edit_post_path(p) %>
                </div>
                <div class="post-delete_btn">
                    <%=link_to "削除", post_path(p), method: "delete" %>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<%= form_for(@post, url: posts_path) do |p| %>
<div class="post-form_element">
    <div><%= p.label :title %></div>
    <div><%=p.text_field :title%></div>
</div>
<div class="post-form_element">
    <div><%= p.label :content %></div>
    <div><%=p.text_area :content%></div>
</div>
<div class="post-form_element">
    <%=p.submit%>
</div>
<% end %>

app/views/users/new.html.erb
<div class="signup-form">
    <%= form_for(@user, url: signup_path) do |user| %>
    <div class="signup-form_element">
        <div><%= user.label :email %></div>
        <div><%=user.text_field :email%></div>
    </div>
    <div class="signup-form_element">
        <div><%= user.label :password %></div>
        <div><%=user.password_field :password%></div>
    </div>
    <div class="signup-form_element">
        <div><%= user.label :password_confirmation %></div>
        <div><%=user.password_field :password_confirmation%></div>
    </div>
    <div class="signup-form_element">
        <%=user.submit "登録"%>
    </div>
    <% end %>
</div>